#include <string>

#include "typeid.h"

namespace ufo {

    std::string TYPE_NAMES[] = {
        "NULL",
        "Abstraction",
        "Address",
        "Apply",
        "Array",
        "Async",
        "BinOp",
        "Binding",
        "Boolean",
        "BracketExpr",
        "Closure",
        "Cobegin",
        "Continuation",
        "Do",
        "Evaluator",
        "ExceptionHandler",
        "File",
        "HashTable",
        "Identifier",
        "If",
        "Integer",
        "Iterator",
        "Let",
        "LetIn",
        "LetRec",
        "Loop",
        "List",
        "Nil",
        "Nondet",
        "Primitive",
        "Protocol",
        "Queue",
        "Quote",
        "REPL",
        "Real",
        "Record",
        "RecordDefinition",
        "RecordSpec",
        "SavedEnv",
        "Sequence",
        "Set",
        "Stream",
        "String",
        "StringBuffer",
        "StringStream",
        "Symbol",
        "Term",
        "Triple",
        "TryCatch",
        "Tuple",
        "Unsigned",
        "FINAL"
    };

}
